<a href="https://colab.research.google.com/github/kanika214/PYTHON_TOPICS/blob/main/about_python_kanika.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 'Srings' - An immutable sequence data type

### len() function counts all of the characters in the string, including spaces and punctuation

In [ ]:
#creating a string
Python = 'Hello world!'
print(Python)

#type of variable
type(Python)

# break into new line \n
print('hello\nworld')

len(Python)

Hello world!
hello
world


12

# String Indexing

* We know strings are a sequence, which means Python can use indexes to call parts of the sequence.
* A string index refers to the location of an element present in a string.
* In Python, we use brackets [] after an object to call its index.

In [ ]:
string_index1 = 'I am very confident'
print(string_index1[0])

#last element in index
print(string_index1[-1])

I
t


# String Slicing

*   **colon(:)** (to perform slicing which grabs everything up to a designated point)
* element located at the right index is not included like [1:5]--> 1 to 4 it will show.

In [ ]:
str_slc = 'I am very happy'
print(str_slc[1:5])



print(str_slc[:16])

# to end
print(str_slc[1:])


#Everything
print(str_slc[:])
len(str_slc)

 am 
I am very happy
 am very happy
I am very happy


15

In [ ]:
#we can use the index -4 to extract the FOURTH LAST element

print(str_slc[-4])

a


In [ ]:
## Grab everything, but go in steps size of 1
print(str_slc[::1])

print(str_slc[::2])

# Grab everything, but go in step sizes of 5
print(str_slc[5:15:5])       #(start:stop:step)

I am very happy
Ia eyhpy
vh


# Reverse a string.

In [ ]:
print(str_slc)

I am very happy


In [ ]:
#reverse of string using slicing
print(str_slc[::-1])    # start from -1 then go to 0th index

yppah yrev ma I


## **split()** method Splits the **"string"** at the specified separator, and returns a **"list"**

In [ ]:
st_splt = 'i am an aspiring data scienctist'
print(st_splt.split())

['i', 'am', 'an', 'aspiring', 'data', 'scienctist']


###**join() method** returns a string by joining all the elements of an iterable (list, string, tuple), separated by the given separator.

In [ ]:
text = ['Python', 'is', 'a', 'fun', 'programming', 'language']

# join elements of text with space
print(' '.join(text))


Python is a fun programming language


In [ ]:
i = ['1','2','3']
print(''.join(i))

123


# Reverse a string without changing the position of words.

In [ ]:
string = 'GOOD LUCK'
split = string.split()
emp_str = ""
for i in split:
  emp_str = emp_str+' '+i[::-1]
print(emp_str)



 DOOG KCUL


In [ ]:
#using function
def rev_str(text):
  sp=text.split()
  emp=""
  for char in sp:
    emp=emp+' '+char[::-1]
  return emp
rev_str('I HAVE MY DREAM JOB')


' I EVAH YM MAERD BOJ'

# concatenate strings!

In [ ]:
str1='good'
str2='luck'
print(str1+' '+str2)

#multiply string with int
print(str2*3)

good luck
luckluckluck


# String functions and methods

1. **len()** **function** returns the length of the string
2. **lower()** **method** converts the string to lowercase
3. **upper()** **method** converts the string to uppercase
4. **count()** **method** returns the count of a string in the given string.

 Unlike lower() and upper() method, the count() method takes a string as an argument
5. **find()** **method** returns the index of the first occurrence of a string present in a given string. Similar to the count() method, the find() method takes a string as an argument.
6. **replace()** **method** takes two arguments - 
  * (i) the string to replace and
  * (ii) the string to replace with, and returns a modified string after the operation
7. **capitalize():** method returns a string where the first character is upper case, and the rest is lower case

In [ ]:
#1. len() function
str_len = 'I am learning python'
print(len(str_len))

20


In [ ]:
#2.lower() method
str_low = 'ALL THE BEST'
str_low.lower()

'all the best'

In [ ]:
#3. upper() method
str_up = 'i am very happy'
print(str_up.upper())


I AM VERY HAPPY


In [ ]:
#4. count() method
str_cnt = 'i am happy that i am learning python and sql'
print(str_cnt.count('i am')) 

2


In [ ]:
#5. find() method
str_find = 'i am improving my coding skills'
print(str_find.find('c'))



#find method will return a value of -1 if string is not there
str_find.find('z')

18


-1

In [ ]:
#6. replace() method, takes 2 argument
str_rplc = 'all the best'
print(str_rplc.replace('best','good luck'))

all the good luck


In [ ]:
#7. capitalize() method
str_capital = 'kanika raj'
print(str_capital.capitalize())

Kanika raj


### **isalnum()** Returns True if all characters in the string are alphanumeric

###**isalpha()** Returns True if all characters in the string are in the alphabet

###**isdigit()** Returns True if all characters in the string are digits

In [ ]:
is_num = "kanikaraj"

x = is_num.isalnum()
print(x)

isnm = 'kanikaraj@@'
print(isnm.isalnum())

True
False


In [ ]:
txt = "CompanyX"

x = txt.isalpha()

print(x)

True


In [ ]:
txt = "50800"

x = txt.isdigit()

print(x)

True


## swapcase() Swaps cases, lower case becomes upper case and vice versa.

In [ ]:
txt = "HeLLO,WeLCOME"

x = txt.swapcase()

print(x)

hEllo,wElcome


## **zfill()** Fills the string with a specified number of 0 values at the beginning

In [ ]:
txt = "5"

x = txt.zfill(2)

print(x)

05


# Printing strings a bit differently

In [ ]:
f_name = 'kanika'
l_name = 'raj'
print(f'merge both the strings:-  {f_name} {l_name}')

merge both the strings:-  kanika raj


In [ ]:
print(f_name+' '+l_name)

kanika raj


## Check if any word is present in the given string or not

**To check the certain phrase in a string we use *IN* and *NOT IN* keyword**

In [ ]:
st_wrd = 'i am learning python from basic and soon i will learn advance'
if 'soon' in st_wrd:
    print('True')
else:
    print('n.a')

True


# List- A list is a collection of similar or different types of data.

* **List items are ordered, mutable, and allow duplicate values.**


In [ ]:
list1 = ['a','1','b','2']
print(list1)

#check item
if i in list1:
  print('yes')


['a', '1', 'b', '2']


### Add Elements to a Python List:

* **+**
* **append()**
* **join()**
* **insert()** - method inserts an element to the list at the specified index
* **extend()** - to add all items of one list to another 

In [ ]:
#Add item into a list
l1 = ['Fname','lname','dob','email']+['mobile_no']
print(l1)


['Fname', 'lname', 'dob', 'email', 'mobile_no']


In [ ]:
#2.append()
num_ap = [1,2,3,4,5]
num_ap.append(6)
print(num_ap)

[1, 2, 3, 4, 5, 6]


In [ ]:
#3.join()
l_j = ['hello','kanika_raj']
print(' '.join(l_j))

hello kanika_raj


In [ ]:
#4.insert()
vowel = ['a', 'e', 'i', 'u']
vowel.insert(3, 'o')
print(vowel)

['a', 'e', 'i', 'o', 'u']


In [ ]:
#5. extend()
prime_numbers = [2, 3, 5]
numbers = [1, 4]
numbers.extend(prime_numbers)
print(numbers)

[1, 4, 2, 3, 5]


In [ ]:
# Print all items in the list, one by one:
litems= ['a','b','c']
for i in litems:
  print(i)

a
b
c


In [ ]:
# Print all items by referring to their index number:
list_index = ["a", "b", "c"]
for i in range(len(list_index)):
  print(list_index[i])

a
b
c


In [ ]:
# Print all items, using a while loop to go through all the index numbers

thislist = ["apple", "banana", "cherry"]
i = 0
while i < len(thislist):
  print(thislist[i])
  i = i + 1

apple
banana
cherry


In [ ]:
# Looping using list comprehention

thislist = ["apple", "banana", "cherry"]
print([i for i in thislist])

['apple', 'banana', 'cherry']


## List methods
* pop() - to "pop off" an item from the list.

 By default pop() takes off the element at the last index, but you can also specify which index to pop off.
* remove()
* count()
* index()
* sort()
* reverse()


In [ ]:
#1. pop()
my_list = [1, 2, 3, 1, 1, 1, 3, 10, 5, 8, 'Append me!', 2.73, [1, 2, 3], [10, [19, 20], 30]]

# Pop off the 0 indexed item
my_list.pop()

[10, [19, 20], 30]

In [ ]:
# Assign the popped element, remember default popped index is -1
my_list.pop(11)

2.73

## Use remove() to remove an item/element from the list.
* By default remove() removes the specified element from the list.

* remove() takes the element as an argument.

In [ ]:
my_list = [1, 2, 3, 1, 1, 1, 3, 10, 5, 8, 'Append me!', 2.73, [1, 2, 3], [10, [19, 20], 30]]

# Remove the element which you want to 
my_list.remove([10, [19, 20], 30])
print(my_list)

[1, 2, 3, 1, 1, 1, 3, 10, 5, 8, 'Append me!', 2.73, [1, 2, 3]]


## index()
The index() method returns the index of a specified element.

In [ ]:
my_list.index('Append me!')

10

## sort()
- Use sort() to sort the list in either ascending/descending order

- The sorting is done in ascending order by default

- sort() method takes the reverse boolean as an argument

- sort() method only works on a list with elements of same data type

In [ ]:
new_list = [6, 9, 1, 3, 5]

# Use sort to sort the list (this is permanent!)
new_list.sort()
print(new_list)

[1, 3, 5, 6, 9]


In [ ]:
# Use the reverse boolean to set the ascending or descending order
new_list.sort(reverse=True)
print(new_list)

[9, 6, 5, 3, 1]


In [ ]:
boolean_list = [True, False]

boolean_list.sort(reverse=True)
print(boolean_list)

[True, False]


# reverse()
reverse() method reverses the list

In [ ]:
my_list = [1, 1, 1, 1, 1.43, 2, 3, 3, 5, 8, 10, 'Lubba', 'Dub Dub']
my_list.reverse()
print(my_list)

['Dub Dub', 'Lubba', 10, 8, 5, 3, 3, 2, 1.43, 1, 1, 1, 1]


## clear() Removes all the elements from the list

## List Functions

### len()- function returns the length of the list


In [ ]:
l_length = ['Mean Absolute Error', 'Mean Squared Error', 'Huber Loss', 'Log Loss', 'Hinge Loss', 'Kullback-Leibler']
len(l_length)

6

In [ ]:
fruits = ['apple', 'banana', 'cherry', 'orange']

fruits.clear()

print(fruits)

[]


# Nested Lists- A list inside a list
* [A [list] inside a list].

In [ ]:
# Let's make three lists
lst_1=[1,2,3]
lst_2=['b','a','d']
lst_3=[7,8,9]

# Make a list of lists to form a matrix
list_of_lists = [lst_1,lst_2,lst_3]
print(list_of_lists)

[[1, 2, 3], ['b', 'a', 'd'], [7, 8, 9]]


In [ ]:
# Grab first item in matrix object
list_of_lists[1]

['b', 'a', 'd']

In [ ]:
list_of_lists[1][1]

'a'

## **min()**
**min() function** returns the minimum element of the list

**min() function** only works with lists of similar data types

In [ ]:
new_list = [6, 9, 1, 3, 5.5]
min(new_list)


1

In [ ]:
my_new_list = ['a','b', 'z' ,'y' , 'm']
min(my_new_list)

'a'

## **max()**
**max() function** returns the maximum element of the list

**max() function** only works with lists of similar data types

In [ ]:
new_list = ['Argue','Burglar','Parent','Linear','shape']
max(new_list)

'shape'

## **sum()**
**sum() function** returns the sum of the elements of the list

**sum() function** only works with lists of numeric data types

In [ ]:
new_list = [6, 9, 1, 3, 5.5]
sum(new_list)

24.5

## sorted()
**sorted() function** returns the sorted list

**sorted() function** takes reverse boolean as an argument

**sorted() function** only works on a list with similar data typesNew Section

**sorted() function** does not change our list

In [ ]:
new_list=[6, 9, 1, 3, 5.5]
sorted(new_list)
print(new_list)

[6, 9, 1, 3, 5.5]


In [ ]:
new_list = ['Argue','Burglar','Parent','Linear','shape']
sorted(new_list)

['Argue', 'Burglar', 'Linear', 'Parent', 'shape']

## Tuple- Tuple items are ordered, unchangeable, and allow duplicate values.

* **Tuple items are indexed, the first item has index [0], the second item has index [1] etc.**
* **A tuple can have any number of items and they may be of different types (integer, float, list, string, etc.).**



In [ ]:
# Empty tuple
my_tuple = ()
print(my_tuple)

# Tuple having integers
my_tuple = (1, 2, 3)
print(my_tuple)

# tuple with mixed datatypes
my_tuple = (1, "Hello", 3.4)
print(my_tuple)

# nested tuple
my_tuple = ("mouse", [8, 4, 6], (1, 2, 3))
print(my_tuple)
type(my_tuple)

()
(1, 2, 3)
(1, 'Hello', 3.4)
('mouse', [8, 4, 6], (1, 2, 3))


tuple

## Check if Item Exists

In [ ]:
languages = ('Python', 'Swift', 'C++')

print('C' in languages)    
print('Python' in languages) 

False
True


##**Change Tuple Values**

* Once a tuple is created, you cannot change its values. Tuples are unchangeable, or immutable as it also is called.

* But there is a workaround. You can convert the tuple into a list, change the list, and convert the list back into a tuple.


In [ ]:
x = ("apple", "banana", "cherry")
y = list(x)
y[1] = "kiwi"
x = tuple(y)

print(x)

('apple', 'kiwi', 'cherry')


## Add Items into Tuple



In [ ]:
thistuple = ("apple", "banana", "cherry")
y = list(thistuple)

#add orange
y.append("orange")
thistuple = tuple(y)
print(thistuple)

('apple', 'banana', 'cherry', 'orange')


## count()-  Returns the number of times a specified value occurs in a tuple

In [ ]:
thistuple = (1, 3, 7, 8, 7, 5, 4, 6, 8, 5)

x = thistuple.count(5)

print(x)

2


## **index()**-  Searches the tuple for a specified value and returns the position of where it was found.

In [ ]:
thistuple = (1, 3, 7, 8, 7, 5, 4, 6, 8, 5)

x = thistuple.index(8)

print(x)

3


## zip()
zip() function takes multiple lists as arguments and zips them together

This function returns a list of n-paired tuples where n is the number of lists being zipped

In [ ]:
city_list = ['Delhi','Patna','Cuttack','Guwahati']
river_list = ['Yamuna','Ganga','Mahanadi','Brahmaputra']
city_and_their_rivers = list(zip(city_list,river_list))
city_and_their_rivers

[('Delhi', 'Yamuna'),
 ('Patna', 'Ganga'),
 ('Cuttack', 'Mahanadi'),
 ('Guwahati', 'Brahmaputra')]

## **Set**- **Unoredered, not use index, no dulicate values, mutable**

## **set can't contain another set**

## **Set items can be of any data type**

## It is also possible to use the **set()** constructor to make a set

In [ ]:
# Create an empty set 
empty_set = set()
type(empty_set)

set

In [ ]:
# Create a non-empty set within curly braces
non_empty_set = {1,6,4,'abc'}
type(non_empty_set)
print(non_empty_set)

{1, 'abc', 4, 6}


## We can **cast** a **list** with multiple repeat elements to a **set** to get the **unique elements**.

In [ ]:
# Create a list with repeats
my_list = [1,1,2,2,3,4,5,6,1,1]

# Cast as set to get unique values
my_set = set(my_list)
my_set

{1, 2, 3, 4, 5, 6}

In [ ]:
# But we can have tuples as set elements, they are immutable
my_setup = {1, 2, (2,3)}
my_setup


{(2, 3), 1, 2}

## Set methods

* Once a set is created, cannot change its items, but can **add** new items.

* **add() method** adds an element to a set

* This method takes the element to be added as an argument

In [ ]:
# We add to sets with the add() method
my_set = set()
my_set.add('a')
my_set.add('b')
my_set.add('a')
my_set

{'a', 'b'}

## **update() method** helps to add multiple elements to a set

In [ ]:
my_set = {5,7,9,3}
# add multiple elements
my_set.update([2, 3, 4])
print(my_set)

{2, 3, 4, 5, 7, 9}


## **remove()**- to remove an item/element from the set.

* By default **remove()** removes the specified element from the set.

* **remove()** takes the element as an argument.


In [ ]:
non_empty_set = {1,5,6,73,2}
non_empty_set.remove(5)
non_empty_set

{1, 2, 6, 73}

## The ***del*** keyword will delete the set completely

In [ ]:
thisset = {"apple", "banana", "cherry"}

del thisset

#print(thisset)

##**union() method** returns union of two sets,denoted by the operator **|**

In [ ]:
# Initialize sets A and B and then join by union
A = {1, 2, 3, 4, 5}
B = {4, 5, 6, 7, 8}

A.union(B)


{1, 2, 3, 4, 5, 6, 7, 8}

In [ ]:
# Also denoted by the operator |
A | B

{1, 2, 3, 4, 5, 6, 7, 8}

##**intersection() method** Keep ONLY the Duplicates,denoted by operator &

In [ ]:
A = {1, 2, 3, 4, 5}
B = {4, 5, 6, 7, 8}
A.intersection(B)

{4, 5}

In [ ]:
A&B

{4, 5}

## difference() method returns the difference of two sets.

Difference of the set B from set A i.e, (A - B) is a set of elements that are only in A but not in B

Also denoted by the operator **-**

In [ ]:
A = {1, 2, 3, 4, 5}
B = {4, 5, 6, 7, 8}
print(A.difference(B))
B.difference(A)

{1, 2, 3}


{6, 7, 8}

In [ ]:
print(A-B)
B-A

{1, 2, 3}


{6, 7, 8}

## **symmetric_difference() method**- Keep All, But NOT the Duplicates(excluding the intersection)
Also denoted by the operator **^**

In [ ]:
A = {1, 2, 3, 4, 5}
B = {4, 5, 6, 7, 8}
print(B.symmetric_difference(A))
A^B

{1, 2, 3, 6, 7, 8}


{1, 2, 3, 6, 7, 8}

## Access set Items

In [ ]:
thisset = {"apple", "banana", "cherry"}

for x in thisset:
  print(x)

apple
cherry
banana


In [ ]:
thisset = {"apple", "banana", "cherry"}

print("banana" in thisset)


True


## **Dictionary**
Dictionaries are used to store data values in **key:value pairs** like **{key1:value1,key2:value2,key3:value3}**

A dictionary is a collection which is **ordered**, **changeable** and **do not allow duplicates.**

The values in dictionary items can be of any data type

In [ ]:
# Make a dictionary with {} and : to signify a key and a value
marvel_dict = {'Name':'Thor','Place':'Asgard','Weapon' : 'Hammer', 1:2, 3 : 'power', 'alibies' : ['Ironman','Captain America'], 'abc' : {1:2, 4:5}}

In [ ]:
# Call values by their key
marvel_dict['Place']

'Asgard'

In [ ]:
type(marvel_dict)

dict

In [ ]:
marvel_dict['Name']

'Thor'

## Dictionary Methods

### **keys()**
**keys()** method returns the list of keys in the dictionary object

In [ ]:
marvel_dict.keys()

dict_keys(['Name', 'Place', 'Weapon', 1, 3, 'alibies', 'abc'])

In [ ]:
list(marvel_dict.keys())

['Name', 'Place', 'Weapon', 1, 3, 'alibies', 'abc']

### **values()**method returns the list of values in the dictionary object

In [ ]:
print(marvel_dict)

{'Name': 'Thor', 'Place': 'Asgard', 'Weapon': 'Hammer', 1: 2, 3: 'power', 'alibies': ['Ironman', 'Captain America'], 'abc': {1: 2, 4: 5}}


In [ ]:
list(marvel_dict.values())

['Thor',
 'Asgard',
 'Hammer',
 2,
 'power',
 ['Ironman', 'Captain America'],
 {1: 2, 4: 5}]

### items() method returns the list of the keys and values

In [ ]:
# Get the keys and their corresponding values
list(marvel_dict.items())

[('Name', 'Thor'),
 ('Place', 'Asgard'),
 ('Weapon', 'Hammer'),
 (1, 2),
 (3, 'power'),
 ('alibies', ['Ironman', 'Captain America']),
 ('abc', {1: 2, 4: 5})]

### We can also use the **get()** method to extract a particular value of key-value pair.

In [ ]:
marvel_dict.get('Place')

'Asgard'

### get() method takes the key as an argument and returns None if the key is not found in the dictionary.
We can also set the value to return if a key is not found. This will be passed as the second argument in **get()**

In [ ]:
marvel_dict.get('Place')

'Asgard'

In [ ]:
marvel_dict.get('Random')

In [ ]:
marvel_dict.get('Random','Not Found')
len(marvel_dict)

7

In [ ]:
employee_dict = {'Name':'Sanket','Skills':['Python','Machine Learning','Deep Learning'],'Band':6.0,'Promotion Year':[2016,2018,2020]}

In [ ]:
# Let's call items from the dictionary
employee_dict['Skills']

['Python', 'Machine Learning', 'Deep Learning']

In [ ]:
# Can call an index on that value
employee_dict['Skills'][0]

'Python'

In [ ]:
# Can then even call methods on that value
employee_dict['Skills'][0].upper()

'PYTHON'

In [ ]:
# Add a new key

employee_dict['Designation'] ='Senior Data Scientist'

In [ ]:
employee_dict

{'Name': 'Sanket',
 'Skills': ['Python', 'Machine Learning', 'Deep Learning'],
 'Band': 6.0,
 'Promotion Year': [2016, 2018, 2020],
 'Designation': 'Senior Data Scientist'}

### **update()** You can add an element which is a key-value pair using the update() method

This method takes a dictionary as an argument

In [ ]:
employee_dict.update({'Salary':'2,000,000'})

In [ ]:
employee_dict

{'Name': 'Sanket',
 'Skills': ['Python', 'Machine Learning', 'Deep Learning'],
 'Band': 6.0,
 'Promotion Year': [2016, 2018, 2020],
 'Designation': 'Senior Data Scientist',
 'Salary': '2,000,000'}

### We can also use the **update()** method to update the existing values for a key

In [ ]:
employee_dict.update({'Name' : 'Varun Saini'})
employee_dict

{'Name': 'Varun Saini',
 'Skills': ['Python', 'Machine Learning', 'Deep Learning'],
 'Band': 6.0,
 'Promotion Year': [2016, 2018, 2020],
 'Designation': 'Senior Data Scientist',
 'Salary': '2,000,000'}

### We can affect the values of a key as well without the update() method

In [ ]:
employee_dict['Name']

'Varun Saini'

In [ ]:
# Subtract 123 from the value
employee_dict['Name'] = employee_dict['Name'] + ' ' + 'Raj'

In [ ]:
#Check
employee_dict

{'Name': 'Varun Saini Raj',
 'Skills': ['Python', 'Machine Learning', 'Deep Learning'],
 'Band': 6.0,
 'Promotion Year': [2016, 2018, 2020],
 'Designation': 'Senior Data Scientist',
 'Salary': '2,000,000'}

### dict() We can also create dictionary objects from sequence of items which are pairs. This is done using the dict()method

dict() function takes the list of paired elements as argument

In [ ]:
country_list = ['India','Australia','United States','England']
city_list = ['New Delhi', 'Canberra' , 'Washington DC','London']

country_city_list = list(zip(country_list,city_list))
country_city_list

[('India', 'New Delhi'),
 ('Australia', 'Canberra'),
 ('United States', 'Washington DC'),
 ('England', 'London')]

In [ ]:
dict(country_city_list)

{'India': 'New Delhi',
 'Australia': 'Canberra',
 'United States': 'Washington DC',
 'England': 'London'}

In [ ]:
# Let us create a list of paired tuples
country_city_tuples = [('India','New Delhi'),('Australia','Canberra'),('United States','Washington DC'),('England','London')]

country_city_dict = dict(country_city_tuples)
country_city_dict

{'India': 'New Delhi',
 'Australia': 'Canberra',
 'United States': 'Washington DC',
 'England': 'London'}

### pop() method removes and returns an element from a dictionary having the given key.

This method takes two arguments/parameters

 (i) key - key which is to be searched for removal, 
 
 (ii) default - value which is to be returned when the key is not in the dictionary

In [ ]:
country_city_dict.pop('England')

'London'

In [ ]:
country_city_dict

{'India': 'New Delhi',
 'Australia': 'Canberra',
 'United States': 'Washington DC'}

### list comprehensions

List comprehensions are a tool for transforming one list (any iterable actually) into another list.

In [2]:
# Getting the list of squares using list comprehension
list_of_numbers = [1, 2, 4, 6, 11, 14, 17, 20]
squared_numbers = [number**2 for number in list_of_numbers]
print(squared_numbers)

[1, 4, 16, 36, 121, 196, 289, 400]


### get the squares of only those numbers which are even

In [3]:
# Writing list comprehension using conditionals
even_squared_numbers = [number**2 for number in list_of_numbers if number%2==0]
print(even_squared_numbers)

[4, 16, 36, 196, 400]


### NumPy
* In Python we have lists that serve the purpose of arrays, but they are slow to process.

* NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

* The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy

In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)


[1 2 3 4 5]


(5,)

In [6]:
alma_array = np.array([[1,2,3],[4,5,6]]) 
print(alma_array.shape)

(2, 3)


###ndarray.ndim--This returns the number of array dimensions

In [7]:
#ndarray.ndim
array_of_integers = np.array([0,1,2,3,4,5,6,7,8,9])
print("Dimensions of 'array_of_integers' = ", array_of_integers.ndim)

sample_2d_array = np.array([[1,2,3],[4,5,6]]) 
print("Dimensions of 'sample_2d_array' = ", sample_2d_array.ndim)

Dimensions of 'array_of_integers' =  1
Dimensions of 'sample_2d_array' =  2


### ndarray.size This returns the total number of elements in the array

In [8]:
# Print the size of array
array_of_integers = np.array([0,1,2,3,4,5,6,7,8,9])
print(f"The total number of elements in our array 'array_of_integers' =  {array_of_integers.size}")

sample_2d_array = np.array([[1,2,3],[4,5,6]])
print(f"The total number of elements in our array 'sample_2d_array' =  {sample_2d_array.size}")

The total number of elements in our array 'array_of_integers' =  10
The total number of elements in our array 'sample_2d_array' =  6


### ndarray.dtype - This returns the data type of the array

In [9]:
# Print the dtype of array
my_array = np.array([1,2,3,4,5])
print(my_array.dtype)

int64


### ndarray.astype---This changes the data type of an array

In [10]:
# Create an array
arravali = np.array([2,3,4])
print(arravali)
print(arravali.dtype)

# Change the datatype of the array to float
arravali_ = arravali.astype('float64')
print(arravali_)
print(arravali_.dtype)

# Change the datatype of the array to string
# arravali_ = arravali.astype('string_')
# print(arravali_)
# print(arravali_.dtype)

[2 3 4]
int64
[2. 3. 4.]
float64


In [11]:
#NumPy Array Indexing
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [12]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [13]:
# Array with values from 0 to N
array_with_range = np.arange(5)
array_with_range

array([0, 1, 2, 3, 4])

In [14]:
# To get an array with specified input element of desired shape
# Parameters for the function - np.full(shape,value)
a = np.full((3,3),30)
print(a)

[[30 30 30]
 [30 30 30]
 [30 30 30]]


In [15]:
# convert list to ndarray 
typical_list = [1,2,3]
corresponding_array = np.asarray(typical_list) 
corresponding_array

array([1, 2, 3])

In [16]:
# convert tuple to ndarray
typical_tuple = (1,2,3) 
corresponding_array = np.asarray(typical_tuple) 
corresponding_array

array([1, 2, 3])

# <u> **Array Manipulation**</u>
* ### <code>np.transpose(array)</code> - To transpose array
* ### <code>np.reshape(array,shape)</code> - To Change shape of an array
* ### <code>np.resize(array,shape)</code> - To return new array with shape 
* ### <code>np.flatten(array)</code> - To flatten the array

In [17]:
#np.transpose(array) 
arravali = np.array(np.random.randint(10,45,(8,2)))
print(f"The defined array is \n{arravali}")
print(f" \n The shape of the array is {arravali.shape}")

# Storing the transpose in another matrix object
nilgiri =np.transpose(arravali)
print(f" The transpose of the array is \n{nilgiri}")
print(f" \n The shape of the array is {nilgiri.shape}")

The defined array is 
[[18 16]
 [31 19]
 [34 22]
 [27 29]
 [44 33]
 [39 19]
 [32 15]
 [21 34]]
 
 The shape of the array is (8, 2)
 The transpose of the array is 
[[18 31 34 27 44 39 32 21]
 [16 19 22 29 33 19 15 34]]
 
 The shape of the array is (2, 8)


### What is Pandas?
Pandas is a Python library used for working with data sets.


* Pandas DataFrame consists of three principal components, the data, rows, and columns.
* Pandas allows us to analyze big data and make conclusions based on statistical theories.

* Pandas can clean messy data sets, and make them readable and relevant.
* A Pandas Series is like a column in a table. It is a one-dimensional array holding data of any type.

In [18]:
#Import package
import pandas as pd

# Version of pandas
pd.__version__

'1.3.5'

In [21]:
 #Our first series
number_series = pd.Series([2, 3, 5, 6, 8])
print(number_series)

0    2
1    3
2    5
3    6
4    8
dtype: int64


In [22]:
# Same series but with different indices
number_series = pd.Series([2, 3, 5, 6, 8],index=['a', 'b', 'd','e','f'],name='Number')
print(number_series)

a    2
b    3
d    5
e    6
f    8
Name: Number, dtype: int64


In [23]:
# Initialize list of lists 
list_of_lists = [['Amar', 10], ['Akbar', 15], ['Anthony', 14]]
  
# Create the pandas DataFrame 
df = pd.DataFrame(list_of_lists, columns = ['Name', 'Age']) 
  
# Print dataframe
df

Name  Age
0     Amar   10
1    Akbar   15
2  Anthony   14

### We can print the indices of our dataframe using the index attribute


In [25]:
list(df.index)

[0, 1, 2]

In [24]:
# Store the data in a dictionary 
employee_dict = {'Employee Name':['Rajeev', 'Sumit', 'Aviral'], 'Income':[200000, 140000, 90000]} 
  
# Create DataFrame 
employee_df = pd.DataFrame(employee_dict) 
  
# Print the dataframe
employee_df

Employee Name  Income
0        Rajeev  200000
1         Sumit  140000
2        Aviral   90000

In [19]:
import pandas

mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

myvar = pandas.DataFrame(mydataset)

print(myvar)

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2


In [26]:
# We can use the head() method to see first 5 rows
df.head()

Name  Age
0     Amar   10
1    Akbar   15
2  Anthony   14

In [27]:
df.tail()

Name  Age
0     Amar   10
1    Akbar   15
2  Anthony   14

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    3 non-null      object
 1   Age     3 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 176.0+ bytes
